name: oxygen_tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  quotes_provider: ^1.0.2
  http: ^1.2.1
  auto_size_text: ^3.0.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  show_up_animation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

